version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Pa$$w0rd
    ports:
      - 5432:5432
  nats-streaming:
    image: nats-streaming
    restart: always
    ports:
      - 4222:4222